# AUTO-GENERATED - do not edit by hand.
# ruff: noqa: N815
# Source: PriceFRAME/shared/dist/contracts/workflow-contract.schema.json
# Regenerate via: scripts/sync_contracts.sh
# generated by datamodel-codegen:
#   filename:  workflow-contract.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Id(StrEnum):
    summary = "summary"
    setup_fee = "setup_fee"
    pricing = "pricing"
    pnl = "pnl"
    quoting_summary = "quoting_summary"
    legal = "legal"
    approvals = "approvals"


class ApprovalMode(StrEnum):
    per_tab = "per_tab"
    batch_at_submit = "batch_at_submit"


class Step1(StrEnum):
    summary = "summary"
    setup_fee = "setup_fee"
    pricing = "pricing"
    pnl = "pnl"
    quoting_summary = "quoting_summary"
    legal = "legal"
    approvals = "approvals"


class Prerequisites(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    steps: list[Step1]


class Type(StrEnum):
    string = "string"
    number = "number"
    currency = "currency"
    percentage = "percentage"
    enum = "enum"
    multi_enum = "multi_enum"
    boolean = "boolean"
    date = "date"


class EnumOption(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    value: str
    label: str


class OptionsSource(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["priceframe_api"]
    endpoint: str = Field(..., min_length=1)
    value_path: str = Field(..., min_length=1)
    label_path: str | None = Field(None, min_length=1)
    depends_on: list[str] | None = None
    cache_ttl_seconds: int | None = Field(None, gt=0, le=9007199254740991)


class Validation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    min: float | None = None
    max: float | None = None
    pattern: str | None = None
    decimals: int | None = Field(None, ge=0, le=9007199254740991)
    dependsOn: list[str] | None = None


class Mode(StrEnum):
    proactive = "proactive"
    reactive = "reactive"
    silent = "silent"


class Source(StrEnum):
    historical = "historical"
    market = "market"


class Aggregation(StrEnum):
    median = "median"
    mean = "mean"
    mode = "mode"
    p75 = "p75"


class FilterKey(StrEnum):
    corridor = "corridor"
    service = "service"
    customer_segment = "customer_segment"
    payer = "payer"
    payout_currency = "payout_currency"
    transaction_type = "transaction_type"


class Historical(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    aggregation: Aggregation
    filter_keys: list[FilterKey] = Field(..., min_length=1)
    min_sample_size: int = Field(..., ge=0, le=9007199254740991)


class Market(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    research_query_template: str = Field(..., min_length=1)
    max_age_seconds: int = Field(..., gt=0, le=9007199254740991)


class Suggestion(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    mode: Mode
    sources: list[Source] = Field(..., min_length=1)
    historical: Historical | None = None
    market: Market | None = None
    confidence_threshold: float | None = Field(None, ge=0.0, le=1.0)


class Ui(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    hint: str | None = None
    placeholder: str | None = None
    group: str | None = None


class FieldModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(..., min_length=1)
    label: str = Field(..., min_length=1)
    type: Type
    required: bool
    enum_options: list[EnumOption] | None = None
    options_source: OptionsSource | None = None
    validation: Validation | None = None
    suggestion: Suggestion | None = None
    ui: Ui | None = None
    requires_explicit_confirm: bool | None = None


class EssentialFieldId(RootModel[str]):
    root: str = Field(..., min_length=1)


class OnComplete(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tool: str = Field(..., min_length=1)
    args_template: dict[str, Any]


class Step(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Id
    title: str = Field(..., min_length=1)
    description: str = Field(..., min_length=1)
    approval_mode: ApprovalMode
    prerequisites: Prerequisites | None = None
    fields: list[FieldModel]
    essential_field_ids: list[EssentialFieldId] | None = None
    on_complete: OnComplete | None = None


class FieldId(RootModel[str]):
    root: str = Field(..., min_length=1)


class Phase(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(..., min_length=1)
    field_ids: list[FieldId] = Field(..., min_length=1)


class Conversation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    phases: list[Phase] = Field(..., min_length=1)


class WorkflowContract(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Literal["create_pricing_request"]
    version: str = Field(..., min_length=1)
    title: str = Field(..., min_length=1)
    steps: list[Step]
    conversation: Conversation | None = None
